stages:
  - build
  - verify

latexmk:
  stage: build
  image: aergus/latex

  script: |
    apt-get update && apt-get install -y bzip2 && \
    wget https://perso.ensta-paris.fr/~kielbasi/tikzuml/var/files/src/tikzuml-v1.0-2016-03-29.tbz -O /tmp/tikzuml.tbz && \
    mkdir -p /usr/share/texlive/texmf-dist/tex/latex/tikz-uml && \
    tar -xjf /tmp/tikzuml.tbz -C /usr/share/texlive/texmf-dist/tex/latex/tikz-uml --strip-components=1 && \
    texhash && rm /tmp/tikzuml.tbz
    latexmk thesis && latexmk abstract-cz && latexmk abstract-en;
  artifacts:
    paths:
      - thesis.pdf
      - abstract-cz.pdf
      - abstract-en.pdf

verapdf:
  stage: verify
  image: ghcr.io/mff-cuni-cz/cuni-thesis-validator
  script: |
    verify *.pdf |tee /dev/stderr |grep -qE 'nonCompliant="0"'
